const USER_CALL_FETCH = "USER_CALL_FETCH";
const USER_CALL_SUCCESS = "USER_CALL_SUCCESS";
const USER_CALL_FAILURE = "USER_CALL_FAILURE";

const LOGOUT_CALL_FETCH = "LOGOUT_CALL_FETCH";
const LOGOUT_CALL_SUCCESS = "LOGOUT_CALL_SUCCESS";
const LOGOUT_CALL_FAILURE = "LOGOUT_CALL_FAILURE";

const SET_USER_COLOR = "SET_USER_COLOR";

export {
  LOGOUT_CALL_FETCH,
  LOGOUT_CALL_SUCCESS,
  LOGOUT_CALL_FAILURE,
  USER_CALL_FETCH,
  USER_CALL_SUCCESS,
  USER_CALL_FAILURE,
  SET_USER_COLOR,
};
